version: '3.8'
services:
  gateway:
    build: 
      context: ./gateway
    container_name: gateway
    restart: always
    ports: 
      - '8000:8000'
    networks:
      - starwars
  characters:
    build: 
      context: ./characters
    container_name: characters
    restart: always
    ports: 
      - ':8001'
    networks:
      - starwars
  planets:
    build: 
      context: ./planets
    container_name: planets
    restart: always
    ports: 
      - ':8002'
    networks:
      - starwars
  films:
    build: 
      context: ./films
    container_name: films
    restart: always
    ports: 
      - ':8003'
    networks:
      - starwars
  database:
    build: 
      context: ./database
    container_name: database
    restart: always
    ports: 
      - ':8004'
    networks:
      - starwars
networks:
  starwars:
    driver: bridge